### PR TITLE
Draft section on gts to wis2

### PR DESCRIPTION
**Pull request by kaiwirt**

### CODE REVIEW

**Comment by kaiwirt** [comment]
@KenRJTD: Anything to add from your side?

**Comment by KenRJTD** [comment]
@kaiwirt : "xxg" is still effective?

**Comment by golfvert** [comment]
@KenRJTD is correct. It should be de-dwd-something and jp-jma-something
The something is to be agreed with WMO Sec.

**Comment by kaiwirt** [comment]
@KenRJTD @golfvert 
This is what is in the Pull Request:

for DWD: origin/a/wis2/de-dwd-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC and for JMA: origin/a/wis2/jp-jma-gts-to-wis2/data/[core|recommended]/T1/T2/A1/A2/ii/CCCC

**Comment by KenRJTD** [comment]
(-) Japanese Meteorological Agency (JMA)
(+) Japan Meteorological Agency (JMA)

List of recommendation data (Res1) have not been defined yet, but not sure if additional data (Res40) is appropriate or not. I think All GTS-to-wis2-GWs should share and maintain the list.

We may need an access-controls to allow downloading restricted data (recommended/additional). Will WMO secretariat authorize users? and/or all GCs provide credential (ID and passwd) to all WMO Members?

**Comment by kaiwirt** [comment]
I corrected the name of JMA and added, that the list is shared between the gateways

Not sure about the access control. Maybe grant access upon request based on IP addresses would also work.

**Review by KenRJTD — APPROVED** [review]
@kaiwirt: Thanks.

**Comment by kaiwirt** [comment]
@tomkralidis Can this be merged?

**Review by tomkralidis — APPROVED** [review]

**Pull request merged**
